/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "paper.h"
#include <stdlib.h>

typedef struct {
	int id;
	char author[20];
	char title[20];
	char fileExtension[3];
} Paper;

char * getFileExtension(char *filename) {
	char *token = strtok(filename,".");
    char *extension;

    while (token != NULL)
    {
        extension = token;
        token = strtok(NULL, ".");
    }

    return extension;
}

int findFileLength(char *filename) {
	FILE *fp; 
	fp = fopen(filename, "r");

	if (fp == NULL) {
		printf("File Not Found!\n");
		return -1;
	}

	fseek(fp, 0, SEEK_END);
	int length = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	return length;
}

static Paper *papers = 0;
static int count = 0;

addArgs_out *
add_file_1_svc(addArgs_in *argp, struct svc_req *rqstp)
{
	printf("Add function called!\n");

	if (papers == 0) {
		papers = (Paper*) malloc(15 * sizeof(Paper));
	}

	char newTitle[20];
	static addArgs_out result;

	char fext[20];
	strcpy(fext, argp->fileName);

	if (strcmp(getFileExtension(fext), "pdf") == 0) {
		FILE *fpw;
		snprintf(newTitle, sizeof(newTitle), "%d%s", count, ".pdf");
		fpw = fopen(newTitle, "ab +");

		if (fpw == NULL) {
			perror("fopen");
			printf("Sorry the file cannot be opened");
            exit(1);
		}

		fwrite(argp->content, 1, strlen(argp->content), fpw);
		fclose(fpw);

		if (strlen(argp->content) < 1950) {
			// add file info into array if content < 1950 which means this is the last read buffer from client
			papers[count].id = count;
			strcpy(papers[count].author, argp->author);
			strcpy(papers[count].title, argp->title);
			strcpy(papers[count].fileExtension, "pdf");
			
			// return result
			result.id = count;
			result.author = argp->author;
			result.title = argp->title;
			result.content = argp->content;
			
			count++;
		} else {
			result.id = -1; // client not finished sending read buffer, more to come
		}

		return &result;
	}

	// save file
	snprintf(newTitle, sizeof(newTitle), "%d%s", count, ".doc");
	FILE *fpw;
	fpw = fopen(newTitle, "w+");
	fwrite(argp->content, 1, argp->fileLength, fpw);
	fclose(fpw);

	// add file info into array
	papers[count].id = count;
	strcpy(papers[count].author, argp->author);
	strcpy(papers[count].title, argp->title);
	strcpy(papers[count].fileExtension, "doc");

	// return result
	result.id = count;
	result.author = argp->author;
	result.title = argp->title;
	result.content = argp->content;

	count++;

	return &result;
}

listArgs_out *
list_files_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("List files function called\n");

	static listArgs_out  result_list;
	result_list = malloc(1000 * sizeof(char));

	if (papers == 0) {
		result_list = "\nThere are no files.\n=========================\n";
		return &result_list;
	}

	int i = 0;
    strcpy(result_list, "\n");
	while (i != count) {
		char id[2];
        strcat(result_list, "->ID: ");
		sprintf(id, "%d", papers[i].id);
		strcat(result_list, id);
		strcat(result_list, "\n->Author: ");
		strcat(result_list, papers[i].author);
		strcat(result_list, "\n->Title: ");
		strcat(result_list, papers[i].title);
		strcat(result_list, "\n=========================\n");
		i++;
	}

	return &result_list;
}

detailArgs_out *
detail_file_1_svc(detailArgs_in *argp, struct svc_req *rqstp)
{
	static detailArgs_out  result;

	printf("Detail file function called\n");

	int id = *argp;
	char fileTitle[20];
	snprintf(fileTitle, sizeof(fileTitle), "%d.%s", id, papers[id].fileExtension);

	FILE *fp;
	fp = fopen(fileTitle, "r");

	char *errorMsg = malloc(100 * sizeof(char));

	if (fp == NULL) {
		printf("File Not Found!\n");
		char idString[2];
		strcpy(errorMsg, "No file with ID ");
		sprintf(idString, "%d", id);
		strcat(errorMsg, idString);
		strcat(errorMsg, "\n");
		result.id = -1;
		result.author = errorMsg;
		result.title = errorMsg;
		return &result;
	}

	result.id = papers[id].id;
	result.author = papers[id].author;
	result.title = papers[id].title;

	return &result;
}

fetchArgs_out *
fetch_file_1_svc(fetchArgs_in *argp, struct svc_req *rqstp)
{
	static fetchArgs_out  result;

	printf("Fetch file function called\n");

	int id = *argp;
	char fileTitle[20];
	snprintf(fileTitle, sizeof(fileTitle), "%d%s", id, ".doc");
	FILE *fp;
	fp = fopen(fileTitle, "r");

	char *buffer;
	char *errorMsg = malloc(100 * sizeof(char));

	if (fp == NULL) {
		printf("File Not Found!\n");
		char idString[2];
		strcpy(errorMsg, "No file with ID ");
		sprintf(idString, "%d", id);
		strcat(errorMsg, idString);
		strcat(errorMsg, "\n");
		result.content = errorMsg;
		return &result;
	}

	int length = findFileLength(fileTitle);
	buffer = malloc(length * sizeof(char));

	if (buffer) {
		fgets(buffer, length, fp);
	}
	fclose(fp);
	result.content = buffer;

	return &result;
}