/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "paper.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

addArgs_out *
add_file_1(addArgs_in *argp, CLIENT *clnt)
{
	static addArgs_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_FILE,
		(xdrproc_t) xdr_addArgs_in, (caddr_t) argp,
		(xdrproc_t) xdr_addArgs_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listArgs_out *
list_files_1(void *argp, CLIENT *clnt)
{
	static listArgs_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LIST_FILES,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listArgs_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

detailArgs_out *
detail_file_1(detailArgs_in *argp, CLIENT *clnt)
{
	static detailArgs_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DETAIL_FILE,
		(xdrproc_t) xdr_detailArgs_in, (caddr_t) argp,
		(xdrproc_t) xdr_detailArgs_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

fetchArgs_out *
fetch_file_1(fetchArgs_in *argp, CLIENT *clnt)
{
	static fetchArgs_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FETCH_FILE,
		(xdrproc_t) xdr_fetchArgs_in, (caddr_t) argp,
		(xdrproc_t) xdr_fetchArgs_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
