/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paper.h"

bool_t
xdr_addArgs_in (XDR *xdrs, addArgs_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fileLength))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->content, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_addArgs_out (XDR *xdrs, addArgs_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->content, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_detailArgs_out (XDR *xdrs, detailArgs_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fetchArgs_out (XDR *xdrs, fetchArgs_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->content, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listArgs_out (XDR *xdrs, listArgs_out *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_detailArgs_in (XDR *xdrs, detailArgs_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fetchArgs_in (XDR *xdrs, fetchArgs_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}
