/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "paper.h"
#include <string.h>

int findFileLength(char *filename) {
	FILE *fp = fopen(filename, "r");

	if (fp == NULL) {
		printf("File Not Found!\n");
		return -1;
	}

	fseek(fp, 0, SEEK_END);
	int length = ftell(fp);
	fseek(fp, 0, SEEK_SET);

	return length;
}

char * getFileContent(char *filename) {
	FILE *fp = fopen(filename, "r");
	char *buffer = 0;

	if (fp == NULL) {
		printf("File Not Found!\n");
		return "";
	}
	int length = findFileLength(filename);
	buffer = malloc(length * sizeof(char));

	if (buffer) {
		fgets(buffer, length, fp);
	}
	fclose(fp);

	return buffer;
}

void
add_prog_1(char *author, char *title, char  *filename, char *host)
{
	CLIENT *clnt;
	addArgs_out  *result_1;
	addArgs_in  add_file_1_arg;

	#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */
	add_file_1_arg.author = author;
	add_file_1_arg.title = title;
	int length = findFileLength(filename);
	add_file_1_arg.fileLength = length;
	char * content = getFileContent(filename);
	add_file_1_arg.content = content;

	result_1 = add_file_1(&add_file_1_arg, clnt);
	if (result_1 == (addArgs_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("\n=========================\n");
	printf("ADDED FILE INFO: ");
	printf("\n=========================\n");
	printf("ID: %d\n", result_1->id);
	printf("Author: %s\n", result_1->author);
	printf("Title: %s\n", result_1->title);
	printf("=========================\n");

	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


void
list_prog_1(char *host)
{
	CLIENT *clnt;
	listArgs_out  *result_1;
	char *list_files_1_arg;

	#ifndef	DEBUG
	clnt = clnt_create (host, LIST_PROG, LIST_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */

	result_1 = list_files_1((void*)&list_files_1_arg, clnt);
	if (result_1 == (listArgs_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("\n=========================\n");
	printf("LIST OF ALL FILES:");
	printf("\n=========================");
	printf("%s\n", *result_1);

	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


void
detail_prog_1(int id, char *host)
{
	CLIENT *clnt;
	detailArgs_out  *result_1;
	detailArgs_in  detail_file_1_arg = id;

    #ifndef	DEBUG
	clnt = clnt_create (host, DETAIL_PROG, DETAIL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */

	result_1 = detail_file_1(&detail_file_1_arg, clnt);
	if (result_1 == (detailArgs_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("\n=========================\n");
	printf("DETAIL FOR ID: %d\n", id);
	printf("=========================\n");
	if (result_1->id == -1) {
		printf("%s\n", result_1->author);
	} else {
		printf("Author: %s\n", result_1->author);
		printf("Title: %s\n", result_1->title);
	}
	printf("=========================\n");

	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


void
fetch_prog_1(int id, char *host)
{
	CLIENT *clnt;
	fetchArgs_out  *result_1;
	fetchArgs_in  fetch_file_1_arg = id;

	#ifndef	DEBUG
	clnt = clnt_create (host, FETCH_PROG, FETCH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */

	result_1 = fetch_file_1(&fetch_file_1_arg, clnt);
	if (result_1 == (fetchArgs_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("\n=========================\n");
	printf("FILE CONTENT OF ID: %d\n", id);
	printf("=========================\n");
	printf("%s\n", result_1->content);
	printf("=========================\n");

	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *command;
	int id;
	char *author;
	char *title;
	char *filename;


	if (argc < 2) {
		// print out command options
		printf("Usage: %s [option] [server_host] [args]\n", argv[0]);
		printf ("-[option]: add, list, detail, fetch.\n");
		printf("-[server_host]: IP address of server\n");
		printf("-[args]: \n");
		printf("\t-for add -> [author] [title] [file]\n");
		printf("\t-for list -> none\n");
		printf("\t-for detail -> [id]\n");
		printf("\t-for fetch -> [id]\n");
		exit (1);
	}
	
	command = argv[1];
	host = argv[2];

	if (strcmp(command, "add") == 0 && argc == 6)
	{
		author = argv[3];
		title = argv[4];
		filename = argv[5];
		add_prog_1 (author, title, filename, host);
	} 
	else if (strcmp(command, "list") == 0 && argc == 3) 
	{
		list_prog_1 (host);
	}
	else if (strcmp(command, "detail") == 0 && argc == 4)
	{
		id = atoi(argv[3]);
		detail_prog_1(id, host);
	}
	else if (strcmp(command, "fetch") == 0 && argc == 4) 
	{
		id = atoi(argv[3]);
		fetch_prog_1(id, host);
	} 
	else {
		printf("Incorrect command!\n");
		printf("./paper_client to see available commands.\n");
	}

	exit (0);
}
