/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAPER_H_RPCGEN
#define _PAPER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct addArgs_in {
	char *author;
	char *title;
	int fileLength;
	char *content;
};
typedef struct addArgs_in addArgs_in;

struct addArgs_out {
	int id;
	char *author;
	char *title;
	char *content;
};
typedef struct addArgs_out addArgs_out;

struct detailArgs_out {
	int id;
	char *author;
	char *title;
};
typedef struct detailArgs_out detailArgs_out;

struct fetchArgs_out {
	int id;
	char *content;
};
typedef struct fetchArgs_out fetchArgs_out;

typedef char *listArgs_out;

typedef int detailArgs_in;

typedef int fetchArgs_in;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_FILE 1
extern  addArgs_out * add_file_1(addArgs_in *, CLIENT *);
extern  addArgs_out * add_file_1_svc(addArgs_in *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_FILE 1
extern  addArgs_out * add_file_1();
extern  addArgs_out * add_file_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

#define LIST_PROG 0x23451112
#define LIST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LIST_FILES 1
extern  listArgs_out * list_files_1(void *, CLIENT *);
extern  listArgs_out * list_files_1_svc(void *, struct svc_req *);
extern int list_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LIST_FILES 1
extern  listArgs_out * list_files_1();
extern  listArgs_out * list_files_1_svc();
extern int list_prog_1_freeresult ();
#endif /* K&R C */

#define DETAIL_PROG 0x23451113
#define DETAIL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DETAIL_FILE 1
extern  detailArgs_out * detail_file_1(detailArgs_in *, CLIENT *);
extern  detailArgs_out * detail_file_1_svc(detailArgs_in *, struct svc_req *);
extern int detail_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DETAIL_FILE 1
extern  detailArgs_out * detail_file_1();
extern  detailArgs_out * detail_file_1_svc();
extern int detail_prog_1_freeresult ();
#endif /* K&R C */

#define FETCH_PROG 0x23451114
#define FETCH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FETCH_FILE 1
extern  fetchArgs_out * fetch_file_1(fetchArgs_in *, CLIENT *);
extern  fetchArgs_out * fetch_file_1_svc(fetchArgs_in *, struct svc_req *);
extern int fetch_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FETCH_FILE 1
extern  fetchArgs_out * fetch_file_1();
extern  fetchArgs_out * fetch_file_1_svc();
extern int fetch_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_addArgs_in (XDR *, addArgs_in*);
extern  bool_t xdr_addArgs_out (XDR *, addArgs_out*);
extern  bool_t xdr_detailArgs_out (XDR *, detailArgs_out*);
extern  bool_t xdr_fetchArgs_out (XDR *, fetchArgs_out*);
extern  bool_t xdr_listArgs_out (XDR *, listArgs_out*);
extern  bool_t xdr_detailArgs_in (XDR *, detailArgs_in*);
extern  bool_t xdr_fetchArgs_in (XDR *, fetchArgs_in*);

#else /* K&R C */
extern bool_t xdr_addArgs_in ();
extern bool_t xdr_addArgs_out ();
extern bool_t xdr_detailArgs_out ();
extern bool_t xdr_fetchArgs_out ();
extern bool_t xdr_listArgs_out ();
extern bool_t xdr_detailArgs_in ();
extern bool_t xdr_fetchArgs_in ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAPER_H_RPCGEN */
